-- 1. categories tablosundan parent_id sütununu ve foreign key constraint'ini kaldırıyoruz.
ALTER TABLE categories DROP COLUMN IF EXISTS parent_id;

-- 2. Eğer sıfırdan kurmak isterseniz alternatif komutlar (Dikkat: ürünleri etkiler)
-- DROP TABLE IF EXISTS categories CASCADE;
-- CREATE TABLE categories (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name TEXT NOT NULL,
--   slug TEXT NOT NULL UNIQUE,
--   created_at TIMESTAMPTZ DEFAULT NOW()
-- );
-- ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Public categories are viewable by everyone." ON categories FOR SELECT USING (true);
