-- 1. Mevcut kategorileri temizle
DELETE FROM categories;

-- 2. Sütunları düzenle
ALTER TABLE categories DROP COLUMN IF EXISTS parent_id;
ALTER TABLE categories DROP COLUMN IF EXISTS name;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS main_category TEXT;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS sub_category TEXT;

-- 3. Yeni kategorileri ekle
INSERT INTO categories (main_category, sub_category, slug) VALUES
('Kadın', 'Giyim', 'kadin-giyim'),
('Kadın', 'Ayakkabı', 'kadin-ayakkabi'),
('Kadın', 'Aksesuar & Çanta', 'kadin-aksesuar-canta'),
('Kadın', 'Ev & İç Giyim', 'kadin-ev-ic-giyim'),
('Erkek', 'Giyim', 'erkek-giyim'),
('Erkek', 'Ayakkabı', 'erkek-ayakkabi'),
('Erkek', 'Kişisel Bakım', 'erkek-kisisel-bakim'),
('Erkek', 'Çanta', 'erkek-canta'),
('Erkek', 'Saat & Aksesuar', 'erkek-saat-aksesuar'),
('Erkek', 'İç Giyim', 'erkek-ic-giyim'),
('Erkek', 'Elektronik', 'erkek-elektronik'),
('Anne & Çocuk', 'Bebek', 'anne-cocuk-bebek'),
('Anne & Çocuk', 'Kız Çocuk', 'anne-cocuk-kiz-cocuk'),
('Anne & Çocuk', 'Erkek Çocuk', 'anne-cocuk-erkek-cocuk'),
('Anne & Çocuk', 'Bebek Bakım', 'anne-cocuk-bebek-bakim'),
('Anne & Çocuk', 'Oyuncak', 'anne-cocuk-oyuncak'),
('Anne & Çocuk', 'Beslenme Emzirme', 'anne-cocuk-beslenme-emzirme'),
('Anne & Çocuk', 'Taşıma & Güvenlik', 'anne-cocuk-tasima-guvenlik'),
('Anne & Çocuk', 'Bebek Odası', 'anne-cocuk-bebek-odasi'),
('Ev & Mobilya', 'Sofra & Mutfak', 'ev-mobilya-sofra-mutfak'),
('Ev & Mobilya', 'Ev Gereçleri', 'ev-mobilya-ev-gerecleri'),
('Ev & Mobilya', 'Aydınlatma', 'ev-mobilya-aydinlatma'),
('Ev & Mobilya', 'Ev Tekstil', 'ev-mobilya-ev-tekstil'),
('Ev & Mobilya', 'Ev Dekorasyon', 'ev-mobilya-ev-dekorasyon'),
('Ev & Mobilya', 'Mobilya', 'ev-mobilya-mobilya'),
('Süpermarket', 'Ev & Temizlik', 'supermarket-ev-temizlik'),
('Süpermarket', 'Kişisel Bakım', 'supermarket-kisisel-bakim'),
('Süpermarket', 'Bebek Bakım', 'supermarket-bebek-bakim'),
('Süpermarket', 'Gıda ve İçecek', 'supermarket-gida-ve-icecek'),
('Süpermarket', 'Atıştırmalık', 'supermarket-atistirmalik'),
('Süpermarket', 'Petshop', 'supermarket-petshop'),
('Kozmetik', 'Makyaj', 'kozmetik-makyaj'),
('Kozmetik', 'Cilt Bakımı', 'kozmetik-cilt-bakimi'),
('Kozmetik', 'Parfüm & Deodorant', 'kozmetik-parfum-deodorant'),
('Kozmetik', 'Saç Bakımı', 'kozmetik-sac-bakimi'),
('Kozmetik', 'Kişisel Bakım', 'kozmetik-kisisel-bakim'),
('Kozmetik', 'Saç Şekillendirici', 'kozmetik-sac-sekillendirici'),
('Kozmetik', 'Makyaj Aksesuarları', 'kozmetik-makyaj-aksesuarlari'),
('Kozmetik', 'Epilasyon & Tıraş', 'kozmetik-epilasyon-tiras'),
('Kozmetik', 'Genel Bakım', 'kozmetik-genel-bakim'),
('Elektronik', 'Küçük Ev Aletleri', 'elektronik-kucuk-ev-aletleri'),
('Elektronik', 'Giyilebilir Teknoloji', 'elektronik-giyilebilir-teknoloji'),
('Elektronik', 'Telefon', 'elektronik-telefon'),
('Elektronik', 'Foto & Kamera', 'elektronik-foto-kamera'),
('Elektronik', 'TV & Görüntü & Ses', 'elektronik-tv-goruntu-ses'),
('Elektronik', 'Beyaz Eşya', 'elektronik-beyaz-esya'),
('Elektronik', 'Bilgisayar & Tablet', 'elektronik-bilgisayar-tablet'),
('Elektronik', 'Kişisel Bakım Aletleri', 'elektronik-kisisel-bakim-aletleri'),
('Elektronik', 'Oyunculara Özel', 'elektronik-oyunculara-ozel'),
('Elektronik', 'Elektronik Aksesuarlar', 'elektronik-elektronik-aksesuarlar'),
('Elektronik', 'Klima & Isıtıcılar', 'elektronik-klima-isiticilar'),
('Spor & Outdoor', 'Spor Üst Giyim', 'spor-outdoor-spor-ust-giyim'),
('Spor & Outdoor', 'Spor Alt Giyim', 'spor-outdoor-spor-alt-giyim'),
('Spor & Outdoor', 'Top', 'spor-outdoor-top'),
('Spor & Outdoor', 'Spor Ayakkabı', 'spor-outdoor-spor-ayakkabi'),
('Spor & Outdoor', 'Evde Spor Aletleri', 'spor-outdoor-evde-spor-aletleri'),
('Spor & Outdoor', 'Spor Malzemeleri', 'spor-outdoor-spor-malzemeleri'),
('Spor & Outdoor', 'Bisiklet', 'spor-outdoor-bisiklet'),
('Spor & Outdoor', 'Fitness Kondisyon', 'spor-outdoor-fitness-kondisyon'),
('Spor & Outdoor', 'Sporcu Besinleri', 'spor-outdoor-sporcu-besinleri'),
('Kitap & Kırtasiye', 'Parti Malzemeleri', 'kitap-kirtasiye-parti-malzemeleri'),
('Kitap & Kırtasiye', 'Hobi Malzemeleri', 'kitap-kirtasiye-hobi-malzemeleri'),
('Kitap & Kırtasiye', 'Drone', 'kitap-kirtasiye-drone'),
('Kitap & Kırtasiye', 'Uzaktan Kumandalı Araçlar', 'kitap-kirtasiye-uzaktan-kumandali-araclar'),
('Kitap & Kırtasiye', 'Çakmak Ürünleri', 'kitap-kirtasiye-cakmak-urunleri'),
('Kitap & Kırtasiye', 'Müzik Aletleri', 'kitap-kirtasiye-muzik-aletleri'),
('Kitap & Kırtasiye', 'Hediyelik Ürünler', 'kitap-kirtasiye-hediyelik-urunler'),
('Kitap & Kırtasiye', 'E-kitap Okuyucu', 'kitap-kirtasiye-e-kitap-okuyucu'),
('Kitap & Kırtasiye', 'Din ve Mitoloji', 'kitap-kirtasiye-din-ve-mitoloji'),
('Kitap & Kırtasiye', 'Kişisel Gelişim', 'kitap-kirtasiye-kisisel-gelisim'),
('Kitap & Kırtasiye', 'Hobi, sanat, akademik', 'kitap-kirtasiye-hobi-sanat-akademik'),
('Kitap & Kırtasiye', 'Oyun grupları', 'kitap-kirtasiye-oyun-gruplari'),
('Kitap & Kırtasiye', 'Kırtasiye', 'kitap-kirtasiye-kirtasiye'),
('Kitap & Kırtasiye', 'Yabancı dil kitaplar', 'kitap-kirtasiye-yabanci-dil-kitaplar'),
('Kitap & Kırtasiye', 'Çizgi roman, dergi ve gazete', 'kitap-kirtasiye-cizgi-roman-dergi-ve-gazete'),
('Kitap & Kırtasiye', 'Ofis', 'kitap-kirtasiye-ofis'),
('Kitap & Kırtasiye', 'Kalem', 'kitap-kirtasiye-kalem'),
('Kitap & Kırtasiye', 'Eğitim', 'kitap-kirtasiye-egitim'),
('Kitap & Kırtasiye', 'Boya & Sanatsal Malzemeler', 'kitap-kirtasiye-boya-sanatsal-malzemeler'),
('Kitap & Kırtasiye', 'Çocuk ve Ebeveyn Kitapları', 'kitap-kirtasiye-cocuk-ve-ebeveyn-kitaplari'),
('Kitap & Kırtasiye', 'İş, Ekonomi & Pazarlama', 'kitap-kirtasiye-is-ekonomi-pazarlama');
