-- Otomatik Oluşturulan Kategori Tablosu Güncellemesi

DELETE FROM categories;

-- Ana Kategoriler
INSERT INTO categories (id, name, slug, parent_id) VALUES (1, 'Kozmetik & Kişisel Bakım', 'kozmetik-kisisel-bakim', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (2, 'Kozmetik', 'kozmetik', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (3, 'Süpermarket', 'supermarket', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (4, 'Elektronik', 'elektronik', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (5, 'Ev & Mobilya', 'ev-mobilya', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (6, 'Saat & Aksesuar', 'saat-aksesuar', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (7, 'Spor&Outdoor', 'sporoutdoor', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (8, 'Aksesuar', 'aksesuar', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (9, 'Kadın', 'kadin', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (10, 'Erkek', 'erkek', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (11, 'Ayakkabı', 'ayakkabi', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (12, 'Ayakkabı & Çanta', 'ayakkabi-canta', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (13, 'Anne & Çocuk', 'anne-cocuk', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (14, 'Giyim', 'giyim', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (15, 'Spor & Outdoor', 'spor-outdoor', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (16, 'Çocuk', 'cocuk', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (17, 'Ev ve Mobilya', 'ev-ve-mobilya', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (18, 'Anne & Bebek & Çocuk', 'anne-bebek-cocuk', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (19, 'Otomobil & Motosiklet', 'otomobil-motosiklet', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (20, 'Hobi', 'hobi', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (21, 'Kırtasiye & Ofis Malzemeleri', 'kirtasiye-ofis-malzemeleri', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (22, 'Bahçe & Yapı Market', 'bahce-yapi-market', NULL);
INSERT INTO categories (id, name, slug, parent_id) VALUES (23, 'Kitap', 'kitap', NULL);

-- Alt Kategoriler
INSERT INTO categories (id, name, slug, parent_id) VALUES (1000, 'Maskara', 'kozmetik-kisisel-bakim-maskara', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1001, 'Eyeliner', 'kozmetik-kisisel-bakim-eyeliner', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1002, 'Göz Kalemi', 'kozmetik-kisisel-bakim-goz-kalemi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1003, 'Kapatıcı', 'kozmetik-kisisel-bakim-kapatici', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1004, 'Allık', 'kozmetik-kisisel-bakim-allik', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1005, 'Aydınlatıcı', 'kozmetik-kisisel-bakim-aydinlatici', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1006, 'BB & CC Krem', 'kozmetik-kisisel-bakim-bb-cc-krem', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1007, 'Kontür', 'kozmetik-kisisel-bakim-kontur', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1008, 'Pudra', 'kozmetik-kisisel-bakim-pudra', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1009, 'Takma Tırnak & Aksesuarı', 'kozmetik-kisisel-bakim-takma-tirnak-aksesuari', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1010, 'Yüz Kremi', 'kozmetik-kisisel-bakim-yuz-kremi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1011, 'Yüz Temizleyicileri', 'kozmetik-kisisel-bakim-yuz-temizleyicileri', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1012, 'Yüz Maskesi', 'kozmetik-kisisel-bakim-yuz-maskesi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1013, 'Göz Bakımı', 'kozmetik-kisisel-bakim-goz-bakimi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1014, 'Yüz Peelingi', 'kozmetik-kisisel-bakim-yuz-peelingi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1015, 'El Kremi', 'kozmetik-kisisel-bakim-el-kremi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1016, 'Selülit Kremi', 'kozmetik-kisisel-bakim-selulit-kremi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1017, 'Makyaj Temizleyici', 'kozmetik-kisisel-bakim-makyaj-temizleyici', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1018, 'Yüz Güneş Kremi', 'kozmetik-kisisel-bakim-yuz-gunes-kremi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1019, 'Vücut Spreyi', 'kozmetik-kisisel-bakim-vucut-spreyi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1020, 'Parfüm', 'kozmetik-kisisel-bakim-parfum', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1021, 'Parfüm Seti', 'kozmetik-kisisel-bakim-parfum-seti', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1022, 'Deodorant ve Roll On', 'kozmetik-kisisel-bakim-deodorant-ve-roll-on', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1023, 'Şampuan', 'kozmetik-kisisel-bakim-sampuan', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1024, 'Saç Şekillendirici Ürünler', 'kozmetik-kisisel-bakim-sac-sekillendirici-urunler', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1025, 'Saç Maskesi', 'kozmetik-kisisel-bakim-sac-maskesi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1026, 'Saç Boyası', 'kozmetik-kisisel-bakim-sac-boyasi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1027, 'Saç Köpüğü', 'kozmetik-kisisel-bakim-sac-kopugu', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1028, 'Saç Açıcı Sprey', 'kozmetik-kisisel-bakim-sac-acici-sprey', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1029, 'Saç Kesim Makası', 'kozmetik-kisisel-bakim-sac-kesim-makasi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1030, 'Saç Fırçası ve Tarak', 'kozmetik-kisisel-bakim-sac-fircasi-ve-tarak', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1031, 'Saç Vitamini', 'kozmetik-kisisel-bakim-sac-vitamini', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1032, 'Duş Jeli & Kremi', 'kozmetik-kisisel-bakim-dus-jeli-kremi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1033, 'Saç Bakım', 'kozmetik-kisisel-bakim-sac-bakim', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1034, 'Tıraş & Ağda & Epilasyon', 'kozmetik-kisisel-bakim-tiras-agda-epilasyon', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1035, 'Banyo & Duş Ürünleri', 'kozmetik-kisisel-bakim-banyo-dus-urunleri', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1036, 'Ağız Bakım', 'kozmetik-kisisel-bakim-agiz-bakim', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1037, 'Cilt Bakım', 'kozmetik-kisisel-bakim-cilt-bakim', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1038, 'Islak Tıraş', 'kozmetik-kisisel-bakim-islak-tiras', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1039, 'Göz Makyajı', 'kozmetik-kisisel-bakim-goz-makyaji', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1040, 'Ten Makyajı', 'kozmetik-kisisel-bakim-ten-makyaji', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1041, 'Dudak Makyajı', 'kozmetik-kisisel-bakim-dudak-makyaji', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1042, 'Makyaj Seti', 'kozmetik-kisisel-bakim-makyaj-seti', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1043, 'Oje', 'kozmetik-kisisel-bakim-oje', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1044, 'Fondöten', 'kozmetik-kisisel-bakim-fondoten', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1045, 'Ruj', 'kozmetik-kisisel-bakim-ruj', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1046, 'Dudak Kalemi', 'kozmetik-kisisel-bakim-dudak-kalemi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1047, 'Ağız Çalkalama Suyu', 'kozmetik-kisisel-bakim-agiz-calkalama-suyu', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1048, 'Diş Fırçası', 'kozmetik-kisisel-bakim-dis-fircasi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1049, 'Diş Macunu', 'kozmetik-kisisel-bakim-dis-macunu', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1050, 'Günlük Ped', 'kozmetik-kisisel-bakim-gunluk-ped', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1051, 'Banyo Lifi ve Süngeri', 'kozmetik-kisisel-bakim-banyo-lifi-ve-sungeri', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1052, 'Diş Beyazlatma Ürünü', 'kozmetik-kisisel-bakim-dis-beyazlatma-urunu', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1053, 'Makyaj Aksesuarları', 'kozmetik-kisisel-bakim-makyaj-aksesuarlari', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1054, 'El&Ayak Bakımı', 'kozmetik-kisisel-bakim-elayak-bakimi', 1);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1055, 'Makyaj', 'kozmetik-makyaj', 2);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1056, 'Cilt Bakımı', 'kozmetik-cilt-bakimi', 2);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1057, 'Parfüm & Deodorant', 'kozmetik-parfum-deodorant', 2);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1058, 'Saç Bakımı', 'kozmetik-sac-bakimi', 2);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1059, 'Ağız Bakım', 'kozmetik-agiz-bakim', 2);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1060, 'Erkek Bakım', 'kozmetik-erkek-bakim', 2);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1061, 'Kırtasiye & Ofis', 'supermarket-kirtasiye-ofis', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1062, 'İçecek', 'supermarket-icecek', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1063, 'Diğer', 'supermarket-diger', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1064, 'Gıda', 'supermarket-gida', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1065, 'Ev Bakım & Temizlik', 'supermarket-ev-bakim-temizlik', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1066, 'Pet Shop', 'supermarket-pet-shop', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1067, 'Anne Bebek', 'supermarket-anne-bebek', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1068, 'Biberon & Emzik', 'supermarket-biberon-emzik', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1069, 'Göğüs Pompası', 'supermarket-gogus-pompasi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1070, 'Alıştırma Bardağı', 'supermarket-alistirma-bardagi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1071, 'Bebek Maması', 'supermarket-bebek-mamasi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1072, 'Biberon Emzik Temizleyici', 'supermarket-biberon-emzik-temizleyici', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1073, 'Protein Tozu', 'supermarket-protein-tozu', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1074, 'L-Karnitin & CLA', 'supermarket-l-karnitin-cla', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1075, 'Amino Asit', 'supermarket-amino-asit', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1076, 'Güç & Performans Ürünü', 'supermarket-guc-performans-urunu', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1077, 'Gıda Takviyesi & Vitamin', 'supermarket-gida-takviyesi-vitamin', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1078, 'Kreatin', 'supermarket-kreatin', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1079, 'Protein Shaker', 'supermarket-protein-shaker', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1080, 'Çamaşır Yıkama', 'supermarket-camasir-yikama', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1081, 'Bulaşık Yıkama', 'supermarket-bulasik-yikama', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1082, 'Paspas ve Mop', 'supermarket-paspas-ve-mop', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1083, 'Çamaşır Deterjanı', 'supermarket-camasir-deterjani', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1084, 'Bulaşık Makinesi Deterjanı', 'supermarket-bulasik-makinesi-deterjani', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1085, 'Oda Kokusu', 'supermarket-oda-kokusu', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1086, 'Mutfak & Banyo Temizlik', 'supermarket-mutfak-banyo-temizlik', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1087, 'Çamaşır Yumuşatıcısı', 'supermarket-camasir-yumusaticisi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1088, 'Islak Mendil', 'supermarket-islak-mendil', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1089, 'Tuvalet Kağıdı', 'supermarket-tuvalet-kagidi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1090, 'Kağıt Havlu', 'supermarket-kagit-havlu', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1091, 'Temizlik Bezi', 'supermarket-temizlik-bezi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1092, 'Süt Arttırıcı İçecekler', 'supermarket-sut-arttirici-icecekler', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1093, 'Bebek Ek Besin', 'supermarket-bebek-ek-besin', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1094, 'Bebek Bezi', 'supermarket-bebek-bezi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1095, 'Bebek Bakım ve Kozmetik', 'supermarket-bebek-bakim-ve-kozmetik', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1096, 'Bebek Diş Fırçası', 'supermarket-bebek-dis-fircasi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1097, 'Bebek Diş Macunu', 'supermarket-bebek-dis-macunu', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1098, 'Bebek Temizleme Pamuğu', 'supermarket-bebek-temizleme-pamugu', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1099, 'Bebek Güneş Kremi', 'supermarket-bebek-gunes-kremi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1100, 'Bebek Şampuanı', 'supermarket-bebek-sampuani', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1101, 'Bebek Bakım Örtüsü', 'supermarket-bebek-bakim-ortusu', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1102, 'Çay', 'supermarket-cay', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1103, 'Özel Gıda Ürünü', 'supermarket-ozel-gida-urunu', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1104, 'Atıştırmalık', 'supermarket-atistirmalik', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1105, 'Süt ve Kahvaltılık', 'supermarket-sut-ve-kahvaltilik', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1106, 'Kuru Gıda', 'supermarket-kuru-gida', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1107, 'Kahve', 'supermarket-kahve', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1108, 'Makarna', 'supermarket-makarna', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1109, 'Salça', 'supermarket-salca', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1110, 'Sıvı Yağ', 'supermarket-sivi-yag', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1111, 'Un', 'supermarket-un', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1112, 'Baharat', 'supermarket-baharat', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1113, 'Hazır Çorba', 'supermarket-hazir-corba', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1114, 'Kahvaltılık Gevrek', 'supermarket-kahvaltilik-gevrek', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1115, 'Yulaf Ezmesi', 'supermarket-yulaf-ezmesi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1116, 'Konserve', 'supermarket-konserve', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1117, 'Toz Şeker', 'supermarket-toz-seker', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1118, 'Süt', 'supermarket-sut', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1119, 'Pasta Süsü', 'supermarket-pasta-susu', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1120, 'Bitki Çayı', 'supermarket-bitki-cayi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1121, 'Gazsız İçecek', 'supermarket-gazsiz-icecek', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1122, 'Meyve Kurusu', 'supermarket-meyve-kurusu', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1123, 'Kuruyemiş', 'supermarket-kuruyemis', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1124, 'Cips', 'supermarket-cips', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1125, 'Çikolata', 'supermarket-cikolata', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1126, 'Gofret', 'supermarket-gofret', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1127, 'Bisküvi', 'supermarket-biskuvi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1128, 'Kraker', 'supermarket-kraker', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1129, 'Şekerleme', 'supermarket-sekerleme', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1130, 'Sakız', 'supermarket-sakiz', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1131, 'Protein Bar', 'supermarket-protein-bar', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1132, 'Sağlıklı Atıştırmalıklar', 'supermarket-saglikli-atistirmaliklar', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1133, 'Unlu Mamül', 'supermarket-unlu-mamul', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1134, 'Kek', 'supermarket-kek', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1135, 'Kedi Maması', 'supermarket-kedi-mamasi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1136, 'Kedi Kumu', 'supermarket-kedi-kumu', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1137, 'Köpek Maması', 'supermarket-kopek-mamasi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1138, 'Kedi Vitamini', 'supermarket-kedi-vitamini', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1139, 'Köpek Tasması', 'supermarket-kopek-tasmasi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1140, 'Kuş Ürünleri', 'supermarket-kus-urunleri', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1141, 'Akvaryum Ürünleri', 'supermarket-akvaryum-urunleri', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1142, 'Kedi ve Köpek Taşıma Çantası', 'supermarket-kedi-ve-kopek-tasima-cantasi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1143, 'Kedi Konserve Mamaları', 'supermarket-kedi-konserve-mamalari', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1144, 'Kedi Ödülü', 'supermarket-kedi-odulu', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1145, 'Köpek Ödülü', 'supermarket-kopek-odulu', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1146, 'Kedi Şampuanı', 'supermarket-kedi-sampuani', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1147, 'Kuş Yemi', 'supermarket-kus-yemi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1148, 'Kedi Tırmalaması', 'supermarket-kedi-tirmalamasi', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1149, 'Araba Kokusu', 'supermarket-araba-kokusu', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1150, 'Dezenfektan', 'supermarket-dezenfektan', 3);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1151, 'Beyaz Eşya', 'elektronik-beyaz-esya', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1152, 'Elektrikli Ev Aletleri', 'elektronik-elektrikli-ev-aletleri', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1153, 'Bilgisayar & Tablet', 'elektronik-bilgisayar-tablet', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1154, 'Telefon & Aksesuar', 'elektronik-telefon-aksesuar', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1155, 'Giyilebilir Teknoloji', 'elektronik-giyilebilir-teknoloji', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1156, 'TV & Görüntü', 'elektronik-tv-goruntu', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1157, 'Süpürge', 'elektronik-supurge', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1158, 'Robot Süpürge', 'elektronik-robot-supurge', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1159, 'Dik Süpürge', 'elektronik-dik-supurge', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1160, 'Ütü', 'elektronik-utu', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1161, 'Kahve Makinesi', 'elektronik-kahve-makinesi', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1162, 'Çay Makinesi', 'elektronik-cay-makinesi', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1163, 'Blender Seti', 'elektronik-blender-seti', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1164, 'Tost Makinesi', 'elektronik-tost-makinesi', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1165, 'Su Isıtıcı & Kettle', 'elektronik-su-isitici-kettle', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1166, 'Airfryer & Fritöz', 'elektronik-airfryer-fritoz', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1167, 'Akıllı Saat', 'elektronik-akilli-saat', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1168, 'Akıllı Bileklik', 'elektronik-akilli-bileklik', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1169, 'Sanal Gerçeklik Gözlükleri', 'elektronik-sanal-gerceklik-gozlukleri', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1170, 'Cep Telefonu', 'elektronik-cep-telefonu', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1171, 'Kapak & Kılıf', 'elektronik-kapak-kilif', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1172, 'Şarj Aleti', 'elektronik-sarj-aleti', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1173, 'Powerbank', 'elektronik-powerbank', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1174, 'Kulaklık', 'elektronik-kulaklik', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1175, 'Dijital Fotoğraf Makineleri', 'elektronik-dijital-fotograf-makineleri', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1176, 'Video Kameralar', 'elektronik-video-kameralar', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1177, 'Hafıza Kartı', 'elektronik-hafiza-karti', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1178, 'Televizyon', 'elektronik-televizyon', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1179, 'Uzaktan Kumanda', 'elektronik-uzaktan-kumanda', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1180, 'Soundbar', 'elektronik-soundbar', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1181, 'Projeksiyon Cihazı', 'elektronik-projeksiyon-cihazi', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1182, 'Media Player', 'elektronik-media-player', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1183, 'Hoparlör', 'elektronik-hoparlor', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1184, 'HDMI Kablo', 'elektronik-hdmi-kablo', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1185, 'Kablo & Adaptör', 'elektronik-kablo-adaptor', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1186, 'TV Ekran Koruyucu', 'elektronik-tv-ekran-koruyucu', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1187, 'TV Aksesuarları', 'elektronik-tv-aksesuarlari', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1188, 'Bilgisayar & Tablet Aksesuar', 'elektronik-bilgisayar-tablet-aksesuar', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1189, 'Cep Telefonu Aksesuar', 'elektronik-cep-telefonu-aksesuar', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1190, 'Veri Depolama', 'elektronik-veri-depolama', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1191, 'Klimalar', 'elektronik-klimalar', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1192, 'Kombiler', 'elektronik-kombiler', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1193, 'Isıtıcılar', 'elektronik-isiticilar', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1194, 'Vantilatörler', 'elektronik-vantilatorler', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1195, 'Şofbenler', 'elektronik-sofbenler', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1196, 'Termosifon', 'elektronik-termosifon', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1197, 'Hava Temizleyici', 'elektronik-hava-temizleyici', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1198, 'Hava Nemlendiricisi', 'elektronik-hava-nemlendiricisi', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1199, 'Buzdolabı', 'elektronik-buzdolabi', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1200, 'Çamaşır Makinesi', 'elektronik-camasir-makinesi', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1201, 'Bulaşık Makinesi', 'elektronik-bulasik-makinesi', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1202, 'Kurutma Makinesi', 'elektronik-kurutma-makinesi', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1203, 'Derin Dondurucu', 'elektronik-derin-dondurucu', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1204, 'Ankastre Set', 'elektronik-ankastre-set', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1205, 'Mikrodalga Fırın', 'elektronik-mikrodalga-firin', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1206, 'Aspiratör', 'elektronik-aspirator', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1207, 'Mini&Midi Fırın', 'elektronik-minimidi-firin', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1208, 'Bilgisayar', 'elektronik-bilgisayar', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1209, 'Tablet', 'elektronik-tablet', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1210, 'Bilgisayar Bileşenleri', 'elektronik-bilgisayar-bilesenleri', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1211, 'Monitör', 'elektronik-monitor', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1212, 'Yazıcılar', 'elektronik-yazicilar', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1213, 'Ağ Modem', 'elektronik-ag-modem', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1214, 'Klavye', 'elektronik-klavye', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1215, 'Mouse', 'elektronik-mouse', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1216, 'Grafik Tablet', 'elektronik-grafik-tablet', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1217, 'SSD (Solid State Drive)', 'elektronik-ssd-solid-state-drive', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1218, 'Ram', 'elektronik-ram', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1219, 'Ekran Kartı', 'elektronik-ekran-karti', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1220, 'Saç Düzleştirici', 'elektronik-sac-duzlestirici', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1221, 'Saç Maşası', 'elektronik-sac-masasi', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1222, 'Saç Kurutma Makinesi', 'elektronik-sac-kurutma-makinesi', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1223, 'Tıraş Makinesi', 'elektronik-tiras-makinesi', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1224, 'Tartı', 'elektronik-tarti', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1225, 'Epilatör', 'elektronik-epilator', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1226, 'IPL Lazer Epilasyon Aleti', 'elektronik-ipl-lazer-epilasyon-aleti', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1227, 'Playstation Konsolları', 'elektronik-playstation-konsollari', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1228, 'Xbox Konsolu', 'elektronik-xbox-konsolu', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1229, 'Playstation Oyunları', 'elektronik-playstation-oyunlari', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1230, 'Konsol Aksesuarları', 'elektronik-konsol-aksesuarlari', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1231, 'Oyuncu Bilgisayarı', 'elektronik-oyuncu-bilgisayari', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1232, 'Oyuncu Monitör', 'elektronik-oyuncu-monitor', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1233, 'Oyuncu Kulaklıkları', 'elektronik-oyuncu-kulakliklari', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1234, 'Oyuncu Mouseları', 'elektronik-oyuncu-mouselari', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1235, 'Oyuncu Klavyesi', 'elektronik-oyuncu-klavyesi', 4);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1236, 'Mobilya', 'ev-mobilya-mobilya', 5);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1237, 'Ev Dekorasyon', 'ev-mobilya-ev-dekorasyon', 5);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1238, 'Ev Tekstili', 'ev-mobilya-ev-tekstili', 5);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1239, 'Yapı Market', 'ev-mobilya-yapi-market', 5);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1240, 'Sofra & Mutfak', 'ev-mobilya-sofra-mutfak', 5);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1241, 'Aydınlatma', 'ev-mobilya-aydinlatma', 5);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1242, 'Takı & Mücevher', 'saat-aksesuar-taki-mucevher', 6);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1243, 'Şapka & Bere', 'saat-aksesuar-sapka-bere', 6);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1244, 'Güneş Gözlüğü', 'saat-aksesuar-gunes-gozlugu', 6);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1245, 'Şal & Eşarp', 'saat-aksesuar-sal-esarp', 6);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1246, 'Sporcu Saç Bandı', 'sporoutdoor-sporcu-sac-bandi', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1247, 'Çocuk Bisikleti', 'sporoutdoor-cocuk-bisikleti', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1248, 'Aksiyon Kamera', 'sporoutdoor-aksiyon-kamera', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1249, 'Elektrikli Bisiklet', 'sporoutdoor-elektrikli-bisiklet', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1250, 'Bisiklet Aksesuarı', 'sporoutdoor-bisiklet-aksesuari', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1251, 'Bisiklet Gözlüğü', 'sporoutdoor-bisiklet-gozlugu', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1252, 'Bisiklet Kaskı', 'sporoutdoor-bisiklet-kaski', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1253, 'Koşu Bandı', 'sporoutdoor-kosu-bandi', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1254, 'Dambıl & Ağırlık Plakası', 'sporoutdoor-dambil-agirlik-plakasi', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1255, 'Pilates Malzemeleri', 'sporoutdoor-pilates-malzemeleri', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1256, 'Yoga Minderi', 'sporoutdoor-yoga-minderi', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1257, 'Ağırlık Eldiveni&Kemerler', 'sporoutdoor-agirlik-eldivenikemerler', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1258, 'Pilates Topu', 'sporoutdoor-pilates-topu', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1259, 'Termos', 'sporoutdoor-termos', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1260, 'Spor T-shirt', 'sporoutdoor-spor-t-shirt', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1261, 'Spor Yelek', 'sporoutdoor-spor-yelek', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1262, 'Spor Sweatshirt', 'sporoutdoor-spor-sweatshirt', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1263, 'Spor Atlet', 'sporoutdoor-spor-atlet', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1264, 'Forma', 'sporoutdoor-forma', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1265, 'Spor Mont', 'sporoutdoor-spor-mont', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1266, 'Spor Şapka', 'sporoutdoor-spor-sapka', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1267, 'Eşofman Takımı', 'sporoutdoor-esofman-takimi', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1268, 'Spor Tayt', 'sporoutdoor-spor-tayt', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1269, 'Spor Şort', 'sporoutdoor-spor-sort', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1270, 'Spor Pantolon', 'sporoutdoor-spor-pantolon', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1271, 'Eşofman', 'sporoutdoor-esofman', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1272, 'Top', 'sporoutdoor-top', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1273, 'Direnç Lastiği', 'sporoutdoor-direnc-lastigi', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1274, 'El Yayı', 'sporoutdoor-el-yayi', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1275, 'Pilates Minder ve Mat', 'sporoutdoor-pilates-minder-ve-mat', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1276, 'Boks Eldiveni', 'sporoutdoor-boks-eldiveni', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1277, 'Barfiks & Şınav Barı', 'sporoutdoor-barfiks-sinav-bari', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1278, 'Crossfit', 'sporoutdoor-crossfit', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1279, 'Boks Bandajı', 'sporoutdoor-boks-bandaji', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1280, 'Kürek', 'sporoutdoor-kurek', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1281, 'Kaykay', 'sporoutdoor-kaykay', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1282, 'Paten', 'sporoutdoor-paten', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1283, 'Dağcılık Malzemesi', 'sporoutdoor-dagcilik-malzemesi', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1284, 'Çadır Uyku Tulumu', 'sporoutdoor-cadir-uyku-tulumu', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1285, 'Su Sporları', 'sporoutdoor-su-sporlari', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1286, 'Dalış Malzemeleri', 'sporoutdoor-dalis-malzemeleri', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1287, 'Av & Balıkçılık Malzemeleri', 'sporoutdoor-av-balikcilik-malzemeleri', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1288, 'Tenis', 'sporoutdoor-tenis', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1289, 'Kayak ve Snowboard', 'sporoutdoor-kayak-ve-snowboard', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1290, 'Okçuluk Sporu', 'sporoutdoor-okculuk-sporu', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1291, 'Çadır', 'sporoutdoor-cadir', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1292, 'Sporcu Matarası', 'sporoutdoor-sporcu-matarasi', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1293, 'Bisiklet', 'sporoutdoor-bisiklet', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1294, 'Fitness Aletleri', 'sporoutdoor-fitness-aletleri', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1295, 'Kondisyon Bisikleti', 'sporoutdoor-kondisyon-bisikleti', 7);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1296, 'Toka', 'aksesuar-toka', 8);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1297, 'Kadın Topuklu Ayakkabı', 'kadin-kadin-topuklu-ayakkabi', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1298, 'Kadın Sneaker', 'kadin-kadin-sneaker', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1299, 'Kadın Günlük Ayakkabı', 'kadin-kadin-gunluk-ayakkabi', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1300, 'Kadın Babet', 'kadin-kadin-babet', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1301, 'Kadın Sandalet', 'kadin-kadin-sandalet', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1302, 'Kadın Bot', 'kadin-kadin-bot', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1303, 'Kadın Çizme', 'kadin-kadin-cizme', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1304, 'Kadın Kar Botu', 'kadin-kadin-kar-botu', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1305, 'Kadın Loafer', 'kadin-kadin-loafer', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1306, 'Kadın Çanta', 'kadin-kadin-canta', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1307, 'Kadın Saat', 'kadin-kadin-saat', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1308, 'Kadın Takı & Mücevher', 'kadin-kadin-taki-mucevher', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1309, 'Kadın Cüzdan', 'kadin-kadin-cuzdan', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1310, 'Kadın Atkı', 'kadin-kadin-atki', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1311, 'Kadın Bere', 'kadin-kadin-bere', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1312, 'Kadın Eldiven', 'kadin-kadin-eldiven', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1313, 'Kadın Kemer', 'kadin-kadin-kemer', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1314, 'Kadın Şal', 'kadin-kadin-sal', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1315, 'Giyim', 'kadin-giyim', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1316, 'İç Giyim', 'kadin-ic-giyim', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1317, 'Kadın Sırt Çantası', 'kadin-kadin-sirt-cantasi', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1318, 'Kadın Aksesuar', 'kadin-kadin-aksesuar', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1319, 'Kadın T-Shirt', 'kadin-kadin-t-shirt', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1320, 'Kadın Gömlek', 'kadin-kadin-gomlek', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1321, 'Kadın Jeans', 'kadin-kadin-jeans', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1322, 'Kadın Pantolon', 'kadin-kadin-pantolon', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1323, 'Kadın Mont', 'kadin-kadin-mont', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1324, 'Kadın Bluz', 'kadin-kadin-bluz', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1325, 'Kadın Ceket', 'kadin-kadin-ceket', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1326, 'Kadın Kazak', 'kadin-kadin-kazak', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1327, 'Kadın Trençkot', 'kadin-kadin-trenckot', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1328, 'Kadın Yağmurluk & Rüzgarlık', 'kadin-kadin-yagmurluk-ruzgarlik', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1329, 'Kadın Sweatshirt', 'kadin-kadin-sweatshirt', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1330, 'Kadın Kaban', 'kadin-kadin-kaban', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1331, 'Kadın Hırka', 'kadin-kadin-hirka', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1332, 'Kadın Spor Sütyeni', 'kadin-kadin-spor-sutyeni', 9);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1333, 'Erkek T-Shirt', 'erkek-erkek-t-shirt', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1334, 'Erkek Şort', 'erkek-erkek-sort', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1335, 'Erkek Gömlek', 'erkek-erkek-gomlek', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1336, 'Erkek Eşofman', 'erkek-erkek-esofman', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1337, 'Erkek Pantolon', 'erkek-erkek-pantolon', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1338, 'Erkek Ceket', 'erkek-erkek-ceket', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1339, 'Erkek Jeans', 'erkek-erkek-jeans', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1340, 'Erkek Yelek', 'erkek-erkek-yelek', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1341, 'Erkek Kazak', 'erkek-erkek-kazak', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1342, 'Erkek Mont', 'erkek-erkek-mont', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1343, 'Erkek Takım Elbise', 'erkek-erkek-takim-elbise', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1344, 'Erkek Sweatshirt', 'erkek-erkek-sweatshirt', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1345, 'Giyim', 'erkek-giyim', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1346, 'Erkek Kaban', 'erkek-erkek-kaban', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1347, 'Erkek Hırka', 'erkek-erkek-hirka', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1348, 'Erkek Trençkot', 'erkek-erkek-trenckot', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1349, 'Erkek Palto', 'erkek-erkek-palto', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1350, 'Erkek Yağmurluk & Rüzgarlık', 'erkek-erkek-yagmurluk-ruzgarlik', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1351, 'Erkek Blazer Ceket', 'erkek-erkek-blazer-ceket', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1352, 'Erkek Polar', 'erkek-erkek-polar', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1353, 'Erkek Spor Ayakkabı', 'erkek-erkek-spor-ayakkabi', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1354, 'Erkek Günlük Ayakkabı', 'erkek-erkek-gunluk-ayakkabi', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1355, 'Erkek Yürüyüş Ayakkabısı', 'erkek-erkek-yuruyus-ayakkabisi', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1356, 'Erkek Sneaker', 'erkek-erkek-sneaker', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1357, 'Erkek Klasik Ayakkabı', 'erkek-erkek-klasik-ayakkabi', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1358, 'Erkek Bot', 'erkek-erkek-bot', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1359, 'Erkek Kar Botu', 'erkek-erkek-kar-botu', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1360, 'Erkek Loafer', 'erkek-erkek-loafer', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1361, 'Erkek Ev Terliği', 'erkek-erkek-ev-terligi', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1362, 'Erkek Koşu Ayakkabısı', 'erkek-erkek-kosu-ayakkabisi', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1363, 'Erkek Çizme', 'erkek-erkek-cizme', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1364, 'Erkek Çanta', 'erkek-erkek-canta', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1365, 'Erkek Sırt Çantası', 'erkek-erkek-sirt-cantasi', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1366, 'Erkek Laptop Çantası', 'erkek-erkek-laptop-cantasi', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1367, 'Erkek Aksesuar', 'erkek-erkek-aksesuar', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1368, 'Erkek İç Giyim', 'erkek-erkek-ic-giyim', 10);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1369, 'Krampon', 'ayakkabi-krampon', 11);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1370, 'Spor Terlik', 'ayakkabi-spor-terlik', 11);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1371, 'Sneaker', 'ayakkabi-sneaker', 11);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1372, 'Koşu Ayakkabısı', 'ayakkabi-kosu-ayakkabisi', 11);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1373, 'Halı Saha Ayakkabısı', 'ayakkabi-hali-saha-ayakkabisi', 11);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1374, 'Basketbol Ayakkabısı', 'ayakkabi-basketbol-ayakkabisi', 11);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1375, 'Voleybol Ayakkabısı', 'ayakkabi-voleybol-ayakkabisi', 11);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1376, 'Bot', 'ayakkabi-bot', 11);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1377, 'Sandalet', 'ayakkabi-sandalet', 11);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1378, 'Bot ve Çizme', 'ayakkabi-bot-ve-cizme', 11);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1379, 'Kar Botu', 'ayakkabi-kar-botu', 11);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1380, 'Deniz Ayakkabısı', 'ayakkabi-deniz-ayakkabisi', 11);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1381, 'Kadın Ayakkabı', 'ayakkabi-canta-kadin-ayakkabi', 12);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1382, 'Erkek Ayakkabı', 'ayakkabi-canta-erkek-ayakkabi', 12);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1383, 'Valiz & Seyahat', 'ayakkabi-canta-valiz-seyahat', 12);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1384, 'Kadın Çanta', 'ayakkabi-canta-kadin-canta', 12);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1385, 'Kız Çocuk Giyim', 'anne-cocuk-kiz-cocuk-giyim', 13);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1386, 'Oyuncak', 'anne-cocuk-oyuncak', 13);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1387, 'Erkek Çocuk Giyim', 'anne-cocuk-erkek-cocuk-giyim', 13);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1388, 'Bebek Giyim', 'anne-cocuk-bebek-giyim', 13);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1389, 'Bebek Bakım', 'anne-cocuk-bebek-bakim', 13);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1390, 'Bebek Giyim', 'giyim-bebek-giyim', 14);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1391, 'Hastane Çıkışı', 'giyim-hastane-cikisi', 14);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1392, 'Bebek Body & Zıbın', 'giyim-bebek-body-zibin', 14);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1393, 'Bebek Takımı', 'giyim-bebek-takimi', 14);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1394, 'Elbise', 'giyim-elbise', 14);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1395, 'Ceket', 'giyim-ceket', 14);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1396, 'Etek', 'giyim-etek', 14);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1397, 'Yağmurluk & Rüzgarlık', 'giyim-yagmurluk-ruzgarlik', 14);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1398, 'Çorap', 'giyim-corap', 14);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1399, 'Kamp & Doğa', 'spor-outdoor-kamp-doga', 15);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1400, 'Spor Ekipmanları', 'spor-outdoor-spor-ekipmanlari', 15);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1401, 'Kondisyon & Fitness', 'spor-outdoor-kondisyon-fitness', 15);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1402, 'Spor Giyim', 'spor-outdoor-spor-giyim', 15);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1403, 'Çocuk Hırka', 'cocuk-cocuk-hirka', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1404, 'Çocuk Bere', 'cocuk-cocuk-bere', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1405, 'Çocuk Elbise', 'cocuk-cocuk-elbise', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1406, 'Çocuk Sweatshirt', 'cocuk-cocuk-sweatshirt', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1407, 'Çocuk Spor Ayakkabı', 'cocuk-cocuk-spor-ayakkabi', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1408, 'Çocuk Eşofman', 'cocuk-cocuk-esofman', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1409, 'Çocuk İç Giyim', 'cocuk-cocuk-ic-giyim', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1410, 'Çocuk T-Shirt', 'cocuk-cocuk-t-shirt', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1411, 'Çocuk Tayt', 'cocuk-cocuk-tayt', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1412, 'Çocuk Günlük Ayakkabı', 'cocuk-cocuk-gunluk-ayakkabi', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1413, 'Çocuk Şort', 'cocuk-cocuk-sort', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1414, 'Çocuk Mont', 'cocuk-cocuk-mont', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1415, 'Çocuk Kaban', 'cocuk-cocuk-kaban', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1416, 'Çocuk Abiye Elbise', 'cocuk-cocuk-abiye-elbise', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1417, 'Çocuk Ceket', 'cocuk-cocuk-ceket', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1418, 'Çocuk Pantolon', 'cocuk-cocuk-pantolon', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1419, 'Çocuk Kazak', 'cocuk-cocuk-kazak', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1420, 'Çocuk Bot', 'cocuk-cocuk-bot', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1421, 'Çocuk Şapka & Bere & Eldiven', 'cocuk-cocuk-sapka-bere-eldiven', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1422, 'Çocuk Okul Çantası', 'cocuk-cocuk-okul-cantasi', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1423, 'Çocuk Gömlek', 'cocuk-cocuk-gomlek', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1424, 'Çocuk Boxer', 'cocuk-cocuk-boxer', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1425, 'Çocuk Krampon', 'cocuk-cocuk-krampon', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1426, 'Çocuk Takım Elbise', 'cocuk-cocuk-takim-elbise', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1427, 'Çocuk Çanta', 'cocuk-cocuk-canta', 16);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1428, 'Bebek & Çocuk Battaniyesi', 'ev-ve-mobilya-bebek-cocuk-battaniyesi', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1429, 'Beşik', 'ev-ve-mobilya-besik', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1430, 'Bebek Yatak', 'ev-ve-mobilya-bebek-yatak', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1431, 'Bebek & Çocuk Nevresim Takımı', 'ev-ve-mobilya-bebek-cocuk-nevresim-takimi', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1432, 'Cibinlik', 'ev-ve-mobilya-cibinlik', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1433, 'Oyuncak Dolabı', 'ev-ve-mobilya-oyuncak-dolabi', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1434, 'Bebek Odası Takımı', 'ev-ve-mobilya-bebek-odasi-takimi', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1435, 'Oyuncu Koltuğu', 'ev-ve-mobilya-oyuncu-koltugu', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1436, 'Salon & Oturma Odası', 'ev-ve-mobilya-salon-oturma-odasi', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1437, 'Genç Odası Takımı', 'ev-ve-mobilya-genc-odasi-takimi', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1438, 'Koltuk Takımı', 'ev-ve-mobilya-koltuk-takimi', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1439, 'Mutfak Dolapları', 'ev-ve-mobilya-mutfak-dolaplari', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1440, 'Şifonyer', 'ev-ve-mobilya-sifonyer', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1441, 'Dolaplar', 'ev-ve-mobilya-dolaplar', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1442, 'Gardırop', 'ev-ve-mobilya-gardirop', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1443, 'Zigon Sehpa', 'ev-ve-mobilya-zigon-sehpa', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1444, 'Suluk&Matara', 'ev-ve-mobilya-sulukmatara', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1445, 'Tencere & Setler', 'ev-ve-mobilya-tencere-setler', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1446, 'Tava&Tava Seti', 'ev-ve-mobilya-tavatava-seti', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1447, 'Bardak & Kadeh', 'ev-ve-mobilya-bardak-kadeh', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1448, 'Ütü Masası ve Aksesuarı', 'ev-ve-mobilya-utu-masasi-ve-aksesuari', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1449, 'Aydınlatma', 'ev-ve-mobilya-aydinlatma', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1450, 'Lambader', 'ev-ve-mobilya-lambader', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1451, 'Yatak Odası', 'ev-ve-mobilya-yatak-odasi', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1452, 'Bahçe Balkon Mobilyası', 'ev-ve-mobilya-bahce-balkon-mobilyasi', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1453, 'Çalışma Odası', 'ev-ve-mobilya-calisma-odasi', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1454, 'Yemek Odası Takımı', 'ev-ve-mobilya-yemek-odasi-takimi', 17);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1455, 'Oyuncak Bebek ve Aksesuarı', 'anne-bebek-cocuk-oyuncak-bebek-ve-aksesuari', 18);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1456, 'Akülü Araç', 'anne-bebek-cocuk-akulu-arac', 18);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1457, 'Oyuncak', 'anne-bebek-cocuk-oyuncak', 18);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1458, 'Mama Sandalyesi', 'anne-bebek-cocuk-mama-sandalyesi', 18);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1459, 'Mama Önlüğü', 'anne-bebek-cocuk-mama-onlugu', 18);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1460, 'Çocuk Gereçleri', 'anne-bebek-cocuk-cocuk-gerecleri', 18);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1461, 'Park Yatak ve Oyun Parkı', 'anne-bebek-cocuk-park-yatak-ve-oyun-parki', 18);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1462, 'Deniz&Havuz', 'anne-bebek-cocuk-denizhavuz', 18);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1463, 'Araç İçi Telefon Tutucular', 'otomobil-motosiklet-arac-ici-telefon-tutucular', 19);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1464, 'Oto Aksesuarları', 'otomobil-motosiklet-oto-aksesuarlari', 19);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1465, 'Oto Paspas', 'otomobil-motosiklet-oto-paspas', 19);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1466, 'Lastik', 'otomobil-motosiklet-lastik', 19);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1467, 'Motosiklet Kaskı', 'otomobil-motosiklet-motosiklet-kaski', 19);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1468, 'Kolçak', 'otomobil-motosiklet-kolcak', 19);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1469, 'Motosiklet Eldiveni', 'otomobil-motosiklet-motosiklet-eldiveni', 19);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1470, 'Motosiklet Ayakkabı & Bot', 'otomobil-motosiklet-motosiklet-ayakkabi-bot', 19);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1471, 'Motosiklet Çantası', 'otomobil-motosiklet-motosiklet-cantasi', 19);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1472, 'Parti Malzemeleri', 'hobi-parti-malzemeleri', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1473, 'Müzik', 'hobi-muzik', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1474, 'Hediyelik Ürünler', 'hobi-hediyelik-urunler', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1475, 'Hobi Malzemeleri', 'hobi-hobi-malzemeleri', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1476, 'Uzaktan Kumandalı Araçlar', 'hobi-uzaktan-kumandali-araclar', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1477, 'Drone ve Drone Aksesuarları', 'hobi-drone-ve-drone-aksesuarlari', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1478, 'Oyun Grupları', 'hobi-oyun-gruplari', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1479, 'Hediye Sepeti', 'hobi-hediye-sepeti', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1480, 'Led Işık', 'hobi-led-isik', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1481, 'Düğün, Kına ve Nikah Malzemeleri', 'hobi-dugun-kina-ve-nikah-malzemeleri', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1482, 'Yılbaşı Süsü', 'hobi-yilbasi-susu', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1483, 'Yılbaşı Ağacı', 'hobi-yilbasi-agaci', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1484, 'Balon', 'hobi-balon', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1485, 'Örgü İpi', 'hobi-orgu-ipi', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1486, 'Boncuk', 'hobi-boncuk', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1487, 'Kumaş', 'hobi-kumas', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1488, 'Nakış Kiti', 'hobi-nakis-kiti', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1489, 'Örgü Kiti', 'hobi-orgu-kiti', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1490, 'Tütün & Tütün Aksesuarları', 'hobi-tutun-tutun-aksesuarlari', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1491, 'Pikap&Gramofon', 'hobi-pikapgramofon', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1492, 'Gitar ve Ekipmanları', 'hobi-gitar-ve-ekipmanlari', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1493, 'Plak', 'hobi-plak', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1494, 'Piyano', 'hobi-piyano', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1495, 'Org', 'hobi-org', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1496, 'Puzzle ve Puzzle Aksesuarları', 'hobi-puzzle-ve-puzzle-aksesuarlari', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1497, 'Okey Takımı', 'hobi-okey-takimi', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1498, 'Satranç', 'hobi-satranc', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1499, 'Maket', 'hobi-maket', 20);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1500, 'Defter', 'kirtasiye-ofis-malzemeleri-defter', 21);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1501, 'Ajanda', 'kirtasiye-ofis-malzemeleri-ajanda', 21);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1502, 'Fotokopi & Baskı Kağıtları', 'kirtasiye-ofis-malzemeleri-fotokopi-baski-kagitlari', 21);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1503, 'Kalem', 'kirtasiye-ofis-malzemeleri-kalem', 21);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1504, 'Boya & Resim', 'kirtasiye-ofis-malzemeleri-boya-resim', 21);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1505, 'Dosyalama&Arşivleme', 'kirtasiye-ofis-malzemeleri-dosyalamaarsivleme', 21);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1506, 'Masaüstü Gereçleri', 'kirtasiye-ofis-malzemeleri-masaustu-gerecleri', 21);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1507, 'Ofis Teknolojileri', 'kirtasiye-ofis-malzemeleri-ofis-teknolojileri', 21);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1508, 'Banyo & Yapı Malzemeleri', 'bahce-yapi-market-banyo-yapi-malzemeleri', 22);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1509, 'Elektrikli El Aletleri', 'bahce-yapi-market-elektrikli-el-aletleri', 22);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1510, 'Hırdavat Ürünleri', 'bahce-yapi-market-hirdavat-urunleri', 22);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1511, 'Boya', 'bahce-yapi-market-boya', 22);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1512, 'Matkap', 'bahce-yapi-market-matkap', 22);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1513, 'Ampul', 'bahce-yapi-market-ampul', 22);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1514, 'Akülü Vidalama', 'bahce-yapi-market-akulu-vidalama', 22);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1515, 'Dijital Yayınlar ve E-kitaplar', 'kitap-dijital-yayinlar-ve-e-kitaplar', 23);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1516, 'Kişisel Gelişim Kitapları', 'kitap-kisisel-gelisim-kitaplari', 23);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1517, 'Hobi ve Sanat Kitapları', 'kitap-hobi-ve-sanat-kitaplari', 23);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1518, 'Yabancı Dil Kitaplar', 'kitap-yabanci-dil-kitaplar', 23);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1519, 'Sınav Hazırlık', 'kitap-sinav-hazirlik', 23);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1520, 'Sözlük & İmla Kılavuzu', 'kitap-sozluk-imla-kilavuzu', 23);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1521, 'Çocuk Bakımı&Ebeveynlik', 'kitap-cocuk-bakimiebeveynlik', 23);
INSERT INTO categories (id, name, slug, parent_id) VALUES (1522, 'İş ve Ekonomi Kitapları', 'kitap-is-ve-ekonomi-kitaplari', 23);


-- Ürünlerin category_id Değerlerini Güncelleme

UPDATE products p
SET category_id = c.id
FROM categories c
WHERE c.name = p.sub_category 
  AND c.parent_id = (SELECT id FROM categories WHERE name = p.main_category LIMIT 1);
  
-- Alt kategorisi olmayan ana kategoriye ait ürünler
UPDATE products p
SET category_id = c.id
FROM categories c
WHERE c.name = p.main_category AND c.parent_id IS NULL AND p.sub_category = '';
