-- 1. Eski tabloları sil
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

-- 2. Yeni categories tablosunu oluştur
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  parent_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security (RLS) ayarları
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public categories are viewable by everyone." ON categories FOR SELECT USING (true);

-- 3. Ana Kategorileri Ekle
INSERT INTO categories (name, slug, parent_id) VALUES 
('Kadın', 'kadin', NULL),
('Erkek', 'erkek', NULL),
('Anne & Çocuk', 'anne-cocuk', NULL),
('Ev & Mobilya', 'ev-mobilya', NULL),
('Süpermarket', 'supermarket', NULL),
('Kozmetik', 'kozmetik', NULL),
('Ayakkabı & Çanta', 'ayakkabi-canta', NULL),
('Saat & Aksesuar', 'saat-aksesuar', NULL),
('Elektronik', 'elektronik', NULL),
('Spor & Outdoor', 'spor-outdoor', NULL);

-- 4. Alt Kategorileri Ekle (Parent ID'leri slug üzerinden dinamik buluyoruz)

-- Kadın Alt Kategorileri
INSERT INTO categories (name, slug, parent_id) VALUES 
('Giyim', 'kadin-giyim', (SELECT id FROM categories WHERE slug = 'kadin')),
('Ayakkabı', 'kadin-ayakkabi', (SELECT id FROM categories WHERE slug = 'kadin')),
('Aksesuar & Çanta', 'kadin-aksesuar-canta', (SELECT id FROM categories WHERE slug = 'kadin')),
('İç Giyim', 'kadin-ic-giyim', (SELECT id FROM categories WHERE slug = 'kadin')),
('Spor & Outdoor', 'kadin-spor-outdoor', (SELECT id FROM categories WHERE slug = 'kadin')),
('Kozmetik', 'kadin-kozmetik', (SELECT id FROM categories WHERE slug = 'kadin')),
('Lüks & Tasarımcı', 'kadin-luks-tasarimci', (SELECT id FROM categories WHERE slug = 'kadin'));

-- Erkek Alt Kategorileri
INSERT INTO categories (name, slug, parent_id) VALUES 
('Giyim', 'erkek-giyim', (SELECT id FROM categories WHERE slug = 'erkek')),
('Ayakkabı', 'erkek-ayakkabi', (SELECT id FROM categories WHERE slug = 'erkek')),
('Aksesuar & Çanta', 'erkek-aksesuar-canta', (SELECT id FROM categories WHERE slug = 'erkek')),
('İç Giyim', 'erkek-ic-giyim', (SELECT id FROM categories WHERE slug = 'erkek')),
('Spor & Outdoor', 'erkek-spor-outdoor', (SELECT id FROM categories WHERE slug = 'erkek')),
('Kişisel Bakım', 'erkek-kisisel-bakim', (SELECT id FROM categories WHERE slug = 'erkek')),
('Lüks & Tasarımcı', 'erkek-luks-tasarimci', (SELECT id FROM categories WHERE slug = 'erkek'));

-- Anne & Çocuk Alt Kategorileri
INSERT INTO categories (name, slug, parent_id) VALUES 
('Kız Çocuk Giyim', 'anne-cocuk-kiz-giyim', (SELECT id FROM categories WHERE slug = 'anne-cocuk')),
('Erkek Çocuk Giyim', 'anne-cocuk-erkek-giyim', (SELECT id FROM categories WHERE slug = 'anne-cocuk')),
('Bebek Giyim', 'anne-cocuk-bebek-giyim', (SELECT id FROM categories WHERE slug = 'anne-cocuk')),
('Bebek Bakım', 'anne-cocuk-bebek-bakim', (SELECT id FROM categories WHERE slug = 'anne-cocuk')),
('Beslenme & Emzirme', 'anne-cocuk-beslenme', (SELECT id FROM categories WHERE slug = 'anne-cocuk')),
('Oyuncak', 'anne-cocuk-oyuncak', (SELECT id FROM categories WHERE slug = 'anne-cocuk')),
('Bebek Odası & Güvenlik', 'anne-cocuk-oda-guvenlik', (SELECT id FROM categories WHERE slug = 'anne-cocuk')),
('Anne & Hamile', 'anne-cocuk-anne-hamile', (SELECT id FROM categories WHERE slug = 'anne-cocuk'));

-- Ev & Mobilya Alt Kategorileri
INSERT INTO categories (name, slug, parent_id) VALUES 
('Sofra & Mutfak', 'ev-mobilya-sofra', (SELECT id FROM categories WHERE slug = 'ev-mobilya')),
('Ev Tekstili', 'ev-mobilya-tekstil', (SELECT id FROM categories WHERE slug = 'ev-mobilya')),
('Ev Dekorasyon', 'ev-mobilya-dekorasyon', (SELECT id FROM categories WHERE slug = 'ev-mobilya')),
('Mobilya', 'ev-mobilya-mobilya', (SELECT id FROM categories WHERE slug = 'ev-mobilya')),
('Aydınlatma', 'ev-mobilya-aydinlatma', (SELECT id FROM categories WHERE slug = 'ev-mobilya')),
('Banyo', 'ev-mobilya-banyo', (SELECT id FROM categories WHERE slug = 'ev-mobilya')),
('Ev Gereçleri', 'ev-mobilya-gerecler', (SELECT id FROM categories WHERE slug = 'ev-mobilya')),
('Yapı Market', 'ev-mobilya-yapi-market', (SELECT id FROM categories WHERE slug = 'ev-mobilya'));

-- Süpermarket Alt Kategorileri
INSERT INTO categories (name, slug, parent_id) VALUES 
('Gıda', 'supermarket-gida', (SELECT id FROM categories WHERE slug = 'supermarket')),
('İçecek', 'supermarket-icecek', (SELECT id FROM categories WHERE slug = 'supermarket')),
('Ev Bakım & Temizlik', 'supermarket-temizlik', (SELECT id FROM categories WHERE slug = 'supermarket')),
('Pet Shop', 'supermarket-pet-shop', (SELECT id FROM categories WHERE slug = 'supermarket')),
('Kırtasiye & Ofis', 'supermarket-kirtasiye', (SELECT id FROM categories WHERE slug = 'supermarket'));

-- Kozmetik Alt Kategorileri
INSERT INTO categories (name, slug, parent_id) VALUES 
('Makyaj', 'kozmetik-makyaj', (SELECT id FROM categories WHERE slug = 'kozmetik')),
('Cilt Bakımı', 'kozmetik-cilt-bakim', (SELECT id FROM categories WHERE slug = 'kozmetik')),
('Saç Bakımı', 'kozmetik-sac-bakim', (SELECT id FROM categories WHERE slug = 'kozmetik')),
('Parfüm & Deodorant', 'kozmetik-parfum', (SELECT id FROM categories WHERE slug = 'kozmetik')),
('Erkek Bakım', 'kozmetik-erkek-bakim', (SELECT id FROM categories WHERE slug = 'kozmetik')),
('Ağız Bakım', 'kozmetik-agiz-bakim', (SELECT id FROM categories WHERE slug = 'kozmetik')),
('Güneş Bakım', 'kozmetik-gunes-bakim', (SELECT id FROM categories WHERE slug = 'kozmetik')),
('Cinsel Sağlık', 'kozmetik-cinsel-saglik', (SELECT id FROM categories WHERE slug = 'kozmetik'));

-- Ayakkabı & Çanta Alt Kategorileri
INSERT INTO categories (name, slug, parent_id) VALUES 
('Kadın Ayakkabı', 'ayakkabi-kadin', (SELECT id FROM categories WHERE slug = 'ayakkabi-canta')),
('Erkek Ayakkabı', 'ayakkabi-erkek', (SELECT id FROM categories WHERE slug = 'ayakkabi-canta')),
('Çocuk Ayakkabı', 'ayakkabi-cocuk', (SELECT id FROM categories WHERE slug = 'ayakkabi-canta')),
('Kadın Çanta', 'canta-kadin', (SELECT id FROM categories WHERE slug = 'ayakkabi-canta')),
('Erkek Çanta', 'canta-erkek', (SELECT id FROM categories WHERE slug = 'ayakkabi-canta')),
('Valiz & Seyahat', 'ayakkabi-canta-valiz', (SELECT id FROM categories WHERE slug = 'ayakkabi-canta')),
('Şemsiye & Aksesuar', 'ayakkabi-canta-semsiye', (SELECT id FROM categories WHERE slug = 'ayakkabi-canta'));

-- Saat & Aksesuar Alt Kategorileri
INSERT INTO categories (name, slug, parent_id) VALUES 
('Kadın Saat', 'saat-kadin', (SELECT id FROM categories WHERE slug = 'saat-aksesuar')),
('Erkek Saat', 'saat-erkek', (SELECT id FROM categories WHERE slug = 'saat-aksesuar')),
('Çocuk Saat', 'saat-cocuk', (SELECT id FROM categories WHERE slug = 'saat-aksesuar')),
('Takı & Mücevher', 'aksesuar-taki', (SELECT id FROM categories WHERE slug = 'saat-aksesuar')),
('Güneş Gözlüğü', 'aksesuar-gozluk', (SELECT id FROM categories WHERE slug = 'saat-aksesuar')),
('Şapka & Bere', 'aksesuar-sapka', (SELECT id FROM categories WHERE slug = 'saat-aksesuar')),
('Şal & Eşarp', 'aksesuar-sal', (SELECT id FROM categories WHERE slug = 'saat-aksesuar'));

-- Elektronik Alt Kategorileri
INSERT INTO categories (name, slug, parent_id) VALUES 
('Bilgisayar & Tablet', 'elektronik-bilgisayar', (SELECT id FROM categories WHERE slug = 'elektronik')),
('Telefon & Aksesuar', 'elektronik-telefon', (SELECT id FROM categories WHERE slug = 'elektronik')),
('Beyaz Eşya', 'elektronik-beyaz-esya', (SELECT id FROM categories WHERE slug = 'elektronik')),
('Elektrikli Ev Aletleri', 'elektronik-kucuk-ev', (SELECT id FROM categories WHERE slug = 'elektronik')),
('TV & Görüntü', 'elektronik-tv', (SELECT id FROM categories WHERE slug = 'elektronik')),
('Ses Sistemleri', 'elektronik-ses', (SELECT id FROM categories WHERE slug = 'elektronik')),
('Oyun & Konsol', 'elektronik-oyun', (SELECT id FROM categories WHERE slug = 'elektronik')),
('Giyilebilir Teknoloji', 'elektronik-giyilebilir', (SELECT id FROM categories WHERE slug = 'elektronik'));

-- Spor & Outdoor Alt Kategorileri
INSERT INTO categories (name, slug, parent_id) VALUES 
('Spor Giyim', 'spor-giyim', (SELECT id FROM categories WHERE slug = 'spor-outdoor')),
('Spor Ayakkabı', 'spor-ayakkabi', (SELECT id FROM categories WHERE slug = 'spor-outdoor')),
('Spor Ekipmanları', 'spor-ekipman', (SELECT id FROM categories WHERE slug = 'spor-outdoor')),
('Outdoor Giyim', 'outdoor-giyim', (SELECT id FROM categories WHERE slug = 'spor-outdoor')),
('Outdoor Ayakkabı', 'outdoor-ayakkabi', (SELECT id FROM categories WHERE slug = 'spor-outdoor')),
('Kamp & Doğa', 'spor-kamp', (SELECT id FROM categories WHERE slug = 'spor-outdoor')),
('Kondisyon & Fitness', 'spor-fitness', (SELECT id FROM categories WHERE slug = 'spor-outdoor'));
